databases:
  - name: inventory-db
    plan: free
    region: singapore


services:
  # ================= BACKEND =================
  - type: web
    name: inventory-backend
    runtime: docker
    region: singapore
    plan: starter

    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

      - key: JWT_SECRET
        sync: false

      - key: JWT_EXPIRES_IN
        value: 7d

      - key: FRONTEND_URL
        fromService:
          name: inventory-frontend
          type: web
          property: hostport

      - key: NODE_ENV
        value: production


  # ================= FRONTEND =================
  - type: web
    name: inventory-frontend
    runtime: docker
    region: singapore
    plan: free

    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend

    envVars:
      - key: VITE_API_URL
        fromService:
          name: inventory-backend
          type: web
          property: hostport